name: Infra CI

on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'terraform/**'
  workflow_dispatch:    

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_LOG: DEBUG
      TF_LOG_PATH: ./terraform.log  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive terraform/
        continue-on-error: true

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd ./terraform
          terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -detailed-exitcode -var "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var "aws_region=${{ secrets.AWS_REGION }}" -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        #terraform taint aws_instance.app_server || true , add this if you want to force recreate the instance 
        run: terraform apply -auto-approve -var "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var "aws_region=${{ secrets.AWS_REGION }}" -input=false